export const weatherDescription = {
    0: { descripcion: 'Despejado', icono: '☀️' },
    1: { descripcion: 'Mayormente despejado', icono: '🌤️' },
    2: { descripcion: 'Parcialmente nublado', icono: '⛅' },
    3: { descripcion: 'Nublado', icono: '☁️' },
    45: { descripcion: 'Neblina', icono: '🌫️' },
    48: { descripcion: 'Niebla con escarcha', icono: '🌫️' },
    51: { descripcion: 'Llovizna ligera', icono: '🌦️' },
    53: { descripcion: 'Llovizna moderada', icono: '🌦️' },
    55: { descripcion: 'Llovizna densa', icono: '🌧️' },
    56: { descripcion: 'Llovizna helada ligera', icono: '🌧️' },
    57: { descripcion: 'Llovizna helada densa', icono: '🌧️' },
    61: { descripcion: 'Lluvia ligera', icono: '🌧️' },
    63: { descripcion: 'Lluvia moderada', icono: '🌧️' },
    65: { descripcion: 'Lluvia intensa', icono: '⛈️' },
    66: { descripcion: 'Lluvia helada ligera', icono: '🌧️' },
    67: { descripcion: 'Lluvia helada intensa', icono: '🌧️' },
    71: { descripcion: 'Nieve ligera', icono: '🌨️' },
    73: { descripcion: 'Nieve moderada', icono: '❄️' },
    75: { descripcion: 'Nieve intensa', icono: '❄️' },
    77: { descripcion: 'Granizo', icono: '🌨️' },
    80: { descripcion: 'Chubascos ligeros', icono: '🌦️' },
    81: { descripcion: 'Chubascos moderados', icono: '🌧️' },
    82: { descripcion: 'Chubascos violentos', icono: '⛈️' },
    85: { descripcion: 'Nevadas ligeras', icono: '🌨️' },
    86: { descripcion: 'Nevadas intensas', icono: '❄️' },
    95: { descripcion: 'Tormenta', icono: '⛈️' },
    96: { descripcion: 'Tormenta con granizo ligero', icono: '⛈️' },
    99: { descripcion: 'Tormenta con granizo intenso', icono: '⛈️' }
}